import type { Metadata } from "next";
import Footer from "@components/components/Footer/Footer";

import { proxima_nova } from "./fonts";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={proxima_nova.className}>
      <body>{children}
      <Footer/>
      </body>
    </html>
  );
}
